### ISSUE TITLE
Mozilla recommends: crypt(HMAC(...), ...)?

### ISSUE THREAD

**Issue by rkofman** [gebi/scryptauth#1]
Hey there,

I'm not a security expert, but was researching golang libraries to use for securing passwords, and stumbled across yours. Looks great! :)

I did have one question: [Mozilla recommends](https://blog.mozilla.org/webdev/2012/06/08/lets-talk-about-password-storage/) using HMAC first, and then scrambling the result using bcrypt (or in our case, scrypt): `H: password -> bcrypt(HMAC(password, local_salt), bcrypt_salt)`. In your library, you do those steps in the reverse order.

I'm curious if there are any subtle security implications to doing it the other way around. I'm aware that some strengthening techniques are order dependent, but I don't know whether that applies here? I'm curious if you do.

**Comment by gebi** [comment]
Hi @rkofman,

In case of scrypt there is no need to have an HMAC before, as scrypt itself is using one in it's basic structure. (scrypt is using pbkdf which itself is using hmac_sha256).
The additional HMAC at then end is thought as a "encryption" step to get through security certifications and as an additional step to secure the hashes in the DB against leaks. Just make sure the hmac_key never thouches the DB and you should be fine.

Maybe one note about the `pw_cost` in the encode/decode routines. We don't use them only for pw_cost anymore but as a mapping for `hmac_key` and scrypt cost parameter set.

Call structure with parameters:

```
scryptauth.Hash(user_password, salt, ...)
  -> scrypt.Key(user_password, salt, ...)
    -> pbkdf2.Key(user_password, salt, ..., h sha256.New)
          prf = hmac.New(h, user_password)
          ...
          prf.reset()
          prf.write(salt)
          ...
```

References:
https://github.com/gebi/scryptauth/blob/master/scryptauth.go#L55
https://github.com/golang/crypto/blob/master/scrypt/scrypt.go#L236
https://github.com/golang/crypto/blob/master/pbkdf2/pbkdf2.go#L43

**Comment by rkofman** [comment]
Thanks for the response -- a great, very informative write-up :smile_cat:. For extra context, I did finally realize why the bcrypt recommendation is the way it is: bcrypt implementations generally return a base64 encoded hash + salt + work factor all in one string. So HMACing that value would lose track of the salt + work factor, and make verification impossible. Therefore all bcrypt+HMAC recommendations mention first HMACing the password, and then bcrypting the result, specifically in that order.

I am still a bit confused about the last sentence in your reply above:

> We don't use them only for pw_cost anymore but as a mapping for hmac_key and scrypt cost parameter set.

Are you simply describing the `EncodeBase64` routine? (i.e. it stores the pw_cost, so passwords are verified with the pw_cost they were encoded with) If not, I'm not sure how the pw_cost parameter relates to the hmac_key?

P.S. Thank you so much for taking the time to help. _Very_ much appreciated.

**Comment by gebi** [comment]
Hi @rkofman 

Yea, you are exactly right about bcrypt and HMAC ordering.

As for `pw_cost`, yes i tried to describe our usage of `EncodeBase64` and spectacularly failed ;), sorry!

What i meant is, that the parameter for `pw_cost` is badly named for our current usage.
We do not use it as a direct mapping to pw_cost for scrypt anymore but also encode the used hmac_key AND scrypt parameters into to. (That's also the reason why the encode/decode routines do not directly encode/decode to `ScryptAuth` structs, so you can implement your own "mapping").

We currently use something along the lines of:

```
    "pw_costs" {
        1 => { hmac_key="xxx", scrypt_pw_cost = 14 },
        2 => { hmac_key="yyy", scrypt_pw_cost = 16 },
        3 => { hmac_key="yyy", scrypt_pw_cost = 18 }
    }
```

But how you use it does not really matter, as long as the hmac_key is separate and not stored in your DB.
